### PR TITLE
fix: allow running the action on a PR

### LINKED ISSUE #65: bug: unable to parse git ref for pull requests
I'm attempting to create a workflow which compares the version in a project file against what the generated next version will be.  This is to ensure that devs have updated the version to match appropriately.  
However, this action expects to only run on a branch build and results in this error:

```
Error: 1.0.1-refs/pull/20/merge.0 is not a valid semver.
```

### PR DESCRIPTION
**Pull request by chrisjohnson00**
This fixes #65 

I'm not a TypeScript developer, so please let me know what I can do to improve this.

My use case for this is mentioned in #65, but essentially I run this on a PR workflow against the default branch, in dry run mode so that I can ensure that the project version specified in a project file (.net csproj file in my case) is set appropriately by the developers.  It's one of a few pre-release checks that I want to enforce as we do automatic releases on merge to `main`.

Thanks!

### CODE REVIEW

File: src/action.ts [hunk 1]
```diff
@@ -128,7 +130,13 @@ export default async function main() {
...
       : bump || defaultBump;
 
-    const incrementedVersion = inc(previousVersion, releaseType, identifier);
+    let incrementedVersion: string | null;
+
+    if (isPullRequest) {
+      incrementedVersion = inc(previousVersion, releaseType);
+    } else {
+      incrementedVersion = inc(previousVersion, releaseType, identifier);
+    }
```
Comment (mathieudutour) [inline src/action.ts:139]: I don't really understand this part: if the releaseType isn't `preX`, then the identifier shouldn't matter?

Comment (chrisjohnson00) [reply src/action.ts:139]: I'll test without this block, one of the changes I made after this may negate the need for this.

Comment (chrisjohnson00) [reply src/action.ts]: @mathieudutour I've tested and confirmed it works without this change, I've reverted this change.

**Review by mathieudutour — APPROVED** [review]
Perfect, thanks!

**Comment by sullivanj91** [comment]
FYI I have a use case where I'd like to create a pre-release on a PR when a certain label is added. Seems like this change may be blocking that functionality as it just generates a "proper" release semver.

I switched to using version 5.2 of this action and now I am able to generate pre-release from PR.

**Comment by sullivanj91** [comment]
I #135 was closed and seems related. Was there a resolution here that I am missing?
